[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "quantum-compiler-pulse-level"
version = "2.0.0"
description = "Pulse-Level Microwave Control & Qiskit Pulse Calibration Engine"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
quantum-compiler-pulse-level = "pulse_compiler.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/quantum-compiler-pulse-level"
Repository = "https://github.com/abusuraihsakhri/quantum-compiler-pulse-level.git"
